name: logging
version: 0.11.5-dev

description: >-
  Provides APIs for debugging and error logging. This library introduces
  abstractions similar to those used in other languages, such as the Closure
  JS Logger and java.util.logging.Logger.
homepage: https://github.com/dart-lang/logging

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.3.0
  test: ^1.3.0
